### ISSUE TITLE
Server could not send frame

### ISSUE THREAD

**Issue by someonenot0710** [djvergad/dash#14]
Hi~
I follow the Installation instructions and successfully  get the output
However, I check  the log in dash/model/dash-server.cc
To open the log, I use the command export NS_LOG=DashServer=level_all 

Following is my command to run the simulator
./waf --run 'src/dash/examples/dash-example --users=1 --protocol="ns3::FdashClient" --linkRate=5000Kbps'

Then I get the log like this

DATA WAS JUST SENT!!!
DashServer:DataSend(0x16e3e30)
VidId: 1 rxAv= 0 queue= 39 res= 1547000
Could not send frame
DATA WAS JUST SENT!!!
DashServer:DataSend(0x16e3e30)
VidId: 1 rxAv= 0 queue= 39 res= 1547000
Could not send frame
DATA WAS JUST SENT!!!
DashServer:DataSend(0x16e3e30)
VidId: 1 rxAv= 0 queue= 38 res= 1547000
Could not send frame
DATA WAS JUST SENT!!!
DashServer:DataSend(0x16e3e30)
VidId: 1 rxAv= 0 queue= 38 res= 1547000
Could not send frame
DATA WAS JUST SENT!!!
....

The log "Could not send frame" is from dash-server.cc line 237

It means that sometimes server could not send packets to client
I wonder why this situation happen?
Could this problem be fixed?

**Comment by dilunga1** [comment]
Hey,

Was the build successful? If yes, can you please share the parameters you're using to execute your code and on which platform you're running this ns-3?

**Comment by djvergad** [comment]
I went through the source code, nothing bad happens, it just means that the TCP send buffer was full, so the packet remains in the `m_queues` buffer. It will be sent when there is space in the buffer. The relevant code is at https://github.com/djvergad/dash/blob/f7e375febd83c704c7e0f85aa9b49626ceb0b39a/model/dash-server.cc#L235 You will see that due to the `break` the packet is not dequeued if not sent.
