### ISSUE TITLE
Total buffer capacity

### ISSUE THREAD

**Issue by ghost** [djvergad/dash#18]
hey,issues again  :D
how to set the total buffer capacity? buffer is infinite?can i set an upper limit to buffer?
i didn't see the restrict of buffer in mpeg-play.
another:
how can i run the dash in variable bandwidth condition?

**Comment by djvergad** [comment]
The total buffer capacity is considered unlimited in the current version of the simulator, but it shouldn't be too difficult to change it to have a maximum capacity if that is what you need. 

Regarding the variable bandwidth situation, have a look at issue  #16, where someone has linked a way to achieve something similar to what you are asking. 

I plan to implement both features at some point if a find the time, in the meantime if you implement them yourself please submit a pull request so that others can also benefit from the changes.

**Comment by djvergad** [comment]
Buffer capacity has been implemented in commit f3d0de8d3bee4cd1bf95d3fd8e8a23d6b065f420.

Bandwidth fluctuation example may be found at https://github.com/djvergad/dash/blob/master/examples/link-example.cc
